import 'package:json_annotation/json_annotation.dart';

part 'aiuta_history_image.g.dart';

/// Base class for images in the Aiuta history.
sealed class AiutaHistoryImage {
  /// URL of the image.
  final String url;

  /// Creates an AiutaHistoryImage with the given URL.
  AiutaHistoryImage(this.url);

  /// Converts the AiutaHistoryImage to a JSON object.
  Map<String, dynamic> toJson();
}

/// Represents an image uploaded by the user.
/// Contains an ID that can be reused with the Aiuta API to skip the upload step for previously uploaded images.
@JsonSerializable()
class AiutaUploadedImage extends AiutaHistoryImage {
  /// ID of the uploaded image.
  final String id;

  /// Creates an AiutaUploadedImage with the given ID and URL.
  AiutaUploadedImage({
    required this.id,
    required String url,
  }) : super(url);

  /// Converts the JSON object to an AiutaUploadedImage.
  factory AiutaUploadedImage.fromJson(Map<String, dynamic> json) =>
      _$AiutaUploadedImageFromJson(json);

  /// Converts the AiutaUploadedImage to a JSON object.
  @override
  Map<String, dynamic> toJson() => _$AiutaUploadedImageToJson(this);
}

/// Represents an image generated by the Aiuta API.
/// Contains only the URL of the image.
@JsonSerializable()
class AiutaGeneratedImage extends AiutaHistoryImage {
  /// Creates an AiutaGeneratedImage with the given URL.
  AiutaGeneratedImage({
    required String url,
  }) : super(url);

  /// Converts the JSON object to an AiutaGeneratedImage.
  factory AiutaGeneratedImage.fromJson(Map<String, dynamic> json) =>
      _$AiutaGeneratedImageFromJson(json);

  /// Converts the AiutaGeneratedImage to a JSON object.
  @override
  Map<String, dynamic> toJson() => _$AiutaGeneratedImageToJson(this);
}
